name: CI

on:
  pull_request:
  push:

jobs:
  CI:
    runs-on: ubuntu-18.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: ['5.6', '7.0', '7.1', '7.2', '7.3']
        experimental: [false]
        include:
          - php: '7.4'
            experimental: true
          - php: '8.0'
            experimental: true
          - php: '8.1'
            experimental: true
    env:
      PHP_VERSION: ${{ matrix.php }}
    name: PHP ${{ matrix.php }}
    steps:

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bz2,xml,curl
        env:
          runner: ubuntu-18.04

      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate composer.json
        run: composer validate
        
      - name: Cache composer files
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Install composer packages
        run: composer install --prefer-dist --no-interaction

      - name: Tests Coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: PHP_VERSION
          fail_ci_if_error: true
